name = "packages"
name_pretty = "Package Management"
fixed_order = true
icon = "system-software-install"

[[entries]]
icon = "list-add-symbolic"
text = "Install Package (Official)"
actions = { install = "kitty --class=PackageManager -e system-package-install" }

[[entries]]
icon = "list-add-symbolic"
text = "Install Package (AUR)"
actions = { install_aur = "kitty --class=PackageManager -e system-package-install-aur" }

[[entries]]
icon = "list-remove-symbolic"
text = "Remove Package"
actions = { remove = "kitty --class=PackageManager -e system-package-remove" }

